[build]
  publish = "dist"
  command = "npm install && npm run build"

[context.dev]
  publish = "dist"
  command = "npm install && npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

